name: Data Preprocessing Automation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Automation Preprocessing
      run: |
        python preprocessing/automate_Reza-Rahmawati.py

    - name: Upload Artifact Dataset Terbaru
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-dataset
        path: preprocessing/Midterm_53_group_preprocessed.csv
