name: Automated Preprocessing Pipeline
on:
  push:
    branches: [ main ]  # Akan otomatis jalan setiap kali kamu melakukan commit/push di branch main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Preprocessing Libraries
        run: pip install pandas scikit-learn

      - name: Execute Automation Script
        run: |
          # Masuk ke folder tempat skrip berada, lalu jalankan Python
          cd preprocessing
          python3 automate_Reza-Rahmawati.py
          
      - name: Commit and Push Updated Dataset
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          # Daftarkan file hasil preprocessing terbaru ke git tracking
          git add preprocessing/dataset_preprocessing.csv
          # Lakukan commit hanya jika ada perubahan data baru agar tidak error
          git diff-index --quiet HEAD || git commit -m "chore: automated dataset refresh by GitHub Actions"
          git push
